### ISSUE TITLE
Use of hard-coded passwords is a bad practice 

### ISSUE THREAD

**Issue by akondasif** [puppetlabs/pltraining-userprefs#53]
Greetings,

I am a security researcher, who is looking for security smells in Puppet scripts.
I noticed instances of hard-coded passwords, which are against the best practices
recommended by Common Weakness Enumeration (CWE) [https://cwe.mitre.org/data/definitions/259.html] and also by other security practitioners.
I suggest use of hiera to mitigate this smell. Feedback is welcome.

PR: https://github.com/puppetlabs/pltraining-userprefs/pull/52
Source: https://github.com/puppetlabs/pltraining-userprefs/blob/master/manifests/defaults.pp

**Comment by josephoaks** [comment]
akondasif,

Thank you for your issue. This is not publicly used module, but instead used in training only in a non-production environment. This module is designed in a manner to show basic functionality within Puppet Training courses.

**Comment by akondasif** [comment]
Thanks for the update. Do you think hard-coding passwords can be a problem for production systems?
